"""create celery_task_executions table

Revision ID: 6f83a9e5303c
Revises: f12d6905b289
Create Date: 2026-08-27 20:29:11.712759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f83a9e5303c'
down_revision: Union[str, None] = 'f12d6905b289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
