"""update celery_task_executions table indexes

Revision ID: c27bcf19c697
Revises: 9539e18f1f7c
Create Date: 2026-08-28 00:29:33.241703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27bcf19c697'
down_revision: Union[str, None] = '9539e18f1f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args_hash', table_name='celery_task_executions')
    op.create_index('ix_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args_celery_hash', table_name='celery_task_executions')
    op.create_index('ix_task_name_args_hash', 'celery_task_executions', ['task_name', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###
